### ISSUE TITLE
Analyze/Dissect Open Source Calendar Repositories/Learn JavaScript

### ISSUE THREAD

**Issue by isaacbondoc3** [CS3398-Rust-Buckets/S2017#19]
Analyze/Dissect open source codes and find code that implements features that will be required in SchedMe, such as: Calendar, booking rules, google calendar synchronization, email notification, full customer and appointments management.

**Comment by isaacbondoc3** [comment]
After looking through the source code of FullCalendar.io, I've determined that this calendar written in JavaScript would be of great use to SchedMe. I also, determined that the implementation of the calendar "skeleton" will be very easy to get displayed on to the website. However, the plugins that will be needed for event/user management will need further investigation and deeper JavaScript Knowledge. The documentation and source code for FullCalendar can be found below:

Documentation:
https://fullcalendar.io/docs/

Repository:
https://github.com/fullcalendar/fullcalendar

**Comment by isaacbondoc3** [comment]
JavaScript Learning Artifact.

![javascript learning artifact](https://cloud.githubusercontent.com/assets/25292079/23378868/559d267a-fcfa-11e6-848b-c839c6505425.png)

**Comment by ew1061** [comment]
http://unminify.com/ to decompress the Javascript and make it more readable.
