### ISSUE TITLE
Research UI Ideas

### ISSUE THREAD

**Issue by J-a-m-e-s-o-n** [CS3398-Rust-Buckets/S2017#21]
Compare various similar applications and open source repositiories to get ideas for UI

**Comment by drlehr** [comment]
I would expect to see something done on this by standup.  You also want to add comments and artifacts.

**Comment by J-a-m-e-s-o-n** [comment]
Folder created in repository for image files relevant to UI research

**Comment by J-a-m-e-s-o-n** [comment]
Most, if not all. of Calendar and scheduling apps do not possess direct messaging features among users. The idea to implement the following feature "Built in texting/messaging platform" may be too ambitious with the time we have this semester, unless we end up ahead of schedule.

**Comment by J-a-m-e-s-o-n** [comment]
Further research to be completed over open source JavaScript messaging systems

**Comment by J-a-m-e-s-o-n** [comment]
Splitting into two issues for Calendar UI and Messaging UI

**Comment by J-a-m-e-s-o-n** [comment]
Artifacts added to develop/User_Interface & master/User_Interface on code repository
