### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by treycalvertsp2017** [CS3398-Rust-Buckets/S2017#24]
Implement useful source code found from "dissecting/analyzing open source code Task#19" with goal of getting calendar "Skeleton" displayed below SchedMe header.

**Comment by isaacbondoc3** [comment]
Implementation of some of the source code derived from FullCalendar repository was successful. The attached photo is showing an implementation of very rudimentary website with the SchedMe Header and Calendar "skeleton" below it. This was implemented on DreamWeaver and the code has not yet been uploaded to git. 

![schedme sprint 1 calendar skeleton](https://cloud.githubusercontent.com/assets/25292079/23347266/826d5d44-fc66-11e6-9898-3afb45e13960.png)
