### ISSUE TITLE
building a messaging platform: task #2

### ISSUE THREAD

**Issue by l-a83** [CS3398-Rust-Buckets/S2017#25]

**Comment by treycalvertsp2017** [comment]
![m1](https://cloud.githubusercontent.com/assets/25254478/23344430/dbcb89b2-fc41-11e6-833a-f91d65d7a717.PNG)
![m2](https://cloud.githubusercontent.com/assets/25254478/23344432/dfd9b5f6-fc41-11e6-8381-e26dc7adaeb5.PNG)

Simulation code to run the messaging board side of the application via twilio this piece of code can prove beneficial as tools need to create our messaging system for the app by means of modifying the code to work hand and hand with our app.
