### ISSUE TITLE
Analyze/Dissect Open Source code: Find useful features

### ISSUE THREAD

**Issue by isaacbondoc3** [CS3398-Rust-Buckets/S2017#26]
Analyze/Dissect open source codes and find the code that implements features that will be required in SchedMe, such as: booking rules, google calendar synchronization, email notification, full customer and appointments management. 

Look for booking rules, google calendar synchronization, and email notification.

**Comment by Matthew-Hughes112** [comment]
https://github.com/bcalik/Whatsapp-Desktop

**Comment by Matthew-Hughes112** [comment]
https://github.com/5musketeers/AppointmentManager

**Comment by Matthew-Hughes112** [comment]
https://github.com/azine/email-bundle email notification for web server applications
